### ISSUE TITLE
Object-Oriented code

### ISSUE THREAD

**Issue by vtellapmc** [10up/ads-txt#23]
Hi

I really like the plugin and the fact that it is approved by WordPress VIP to use it. But I was wondering why it is kept procedural. Do you have any plans to convert the code to object-oriented in near future? I believe updating to the object-oriented makes it clean, easy to maintain the code and extend the functionality if required. I’m happy to work on it and submit the patch. Please let me know.

Thanks,
Vinod

**Comment by helen** [comment]
Hi @vtellapmc - thanks for opening an issue to talk about this. I do not have any plans to make changes to a given paradigm or pattern for the sake of doing so, but I'm open to being convinced that there are tangible benefits. What do you think needs to be an object and how do you think that would be structured and interacted with generally? Is there an example of something that would be easier to extend if using objects? I don't want to get too deep into code without any plan but pseudocode or a spec outline might help with understanding here.

**Comment by vtellapmc** [comment]
Hi Helen,

As I said before the code is pretty robust. The main goal we can achieve here is readability and standardization. Once we move the code to class structure it will be really easy to add unit tests as well. if someone wants to overwrite the ads.txt file with the physical file they can just extend Adstxt\Plugin class and overwrite method tenup_display_ads_txt to look up the file and render contents. Same for admin UI, it's easy to extend the class and have a different editor. Also for the people who have standards to use only OOP like us can easily add this plugin to their code base.

PR: https://github.com/10up/ads-txt/pull/24
 Please take a look at this PR and let me know your thoughts.


Thanks,

**Comment by helen** [comment]
Thanks for the PR and more details. My short answer here is that I don't see this plugin moving in that direction anytime soon, if ever. Here are some more detailed thoughts:

* Unfortunately, it would not make sense to change the structure of a publicly released plugin and wrap everything in classes for the sake of one user's use case without further benefit. While I understand that you are working with a requirement that all code be encapsulated in classes, that in itself does not mean that the code is object-oriented programming. I would be curious if that requirement for you is because of actually wanting to interact with everything as objects or if it's a leftover rule from before PHP had namespaces (before PHP 5.3).
* Extension-by-replacement (e.g. extending and overwriting a method) can be a bit of an antipattern in the WordPress hook paradigm and is frequently impossible to maintain back compat with, leading to a significantly higher risk of breaking people's sites in the future. The proposed scenario of having an actual ads.txt file can already be accomplished using existing WordPress hooks, and is a little confusing to me as to why a workflow would be structured that way. If there are hooks that could be added to make this plugin function better in that regard that would also enable other use cases, I am definitely open to hearing about them! Please also feel free to tell me more about that use case, as I may be missing something.
* Unit testing is not inherently simpler with classes, and is frequently made more difficult when classes are used as functional wrappers. For instance, adding actions in constructors makes unit tests very difficult. See [an example](https://github.com/ryanwelcher/wordpress-practical-unit-testing/blob/master/unit-tests/tests/Real_World_Tests.php#L36) that requires usage of `ReflectionClass`. Single functions (or units of code) are easily tested in isolation and do not require instantiating a class to do so. WordPress core has plenty of test coverage where there aren't classes :)

Again, I'm always open to being convinced, but in this case with seeing your PR I don't think we're on the same page about where this plugin needs to go. I'd definitely be open to the argument that the post object that holds the contents of `ads.txt` could exist as a separate type of object (can't extend `WP_Post`, though) but I don't think that really solves what your specific issue is, which is a stylistic requirement.

**Comment by tomjn** [comment]
I'm inclined to agree with Helen, but I would note that procedural code can still be unit tested, as long as good practice is followed. Specifically, dependency injection

**Comment by jeffpaul** [comment]
Closing this as the related PR #24 has also been closed by @vtellapmc.
